### ISSUE TITLE
Previsão de Lançamento.

### ISSUE THREAD

**Issue by EltonRst** [BoletoNet/boletonet2.0#2]
@carloscds Alguma previsão para postar os códigos ?

**Comment by carloscds** [comment]
@EltonRst Estou aguardando o Rodolfo finalizar as homologações.

**Comment by EltonRst** [comment]
@carloscds Muito obrigado pela informação, estou com os dedos coçando para por a mão nesses novos
códigos !

**Comment by carloscds** [comment]
@EltonRst 👍

**Comment by rafd75** [comment]
@EltonRst , boa noite... Da uma olhada no issue https://github.com/BoletoNet/boletonet2.0/issues/1

@carloscds , se quiser, fecha esse...
